### Тестовый запрос с видеофайлом на анализ
POST http://localhost:8080/api/v1/analysis/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTM4NDI1MjMsImlhdCI6MTc1Mzc5OTMyMywiaWQiOjEsIm5hbWUiOiLQmNCy0LDQvSDQmNCy0LDQvdC-0LIiLCJlbWFpbCI6Iml2YW5AZXhhbXBsZS5jb20ifQ.DV8Y25vv-llWuFQaqPPpNB42iosE2YZgsqjCBZV5t3U
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="recording (3).webm"
Content-Type: video/webm

< ./recording (3).webm
--boundary--

### Получение всех анализов пользователя
GET http://localhost:8080/api/v1/analysis/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTM4NDI1MjMsImlhdCI6MTc1Mzc5OTMyMywiaWQiOjEsIm5hbWUiOiLQmNCy0LDQvSDQmNCy0LDQvdC-0LIiLCJlbWFpbCI6Iml2YW5AZXhhbXBsZS5jb20ifQ.DV8Y25vv-llWuFQaqPPpNB42iosE2YZgsqjCBZV5t3U
Content-Type: application/json

###

### Получение истории чата для анализа
GET http://localhost:8080/api/v1/analysis/5674348a-e42a-475c-ac74-ca5f69289f47/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTM4NDI1MjMsImlhdCI6MTc1Mzc5OTMyMywiaWQiOjEsIm5hbWUiOiLQmNCy0LDQvSDQmNCy0LDQvdC-0LIiLCJlbWFpbCI6Iml2YW5AZXhhbXBsZS5jb20ifQ.DV8Y25vv-llWuFQaqPPpNB42iosE2YZgsqjCBZV5t3U
Content-Type: application/json

###

### Отправка сообщения в чат
POST http://localhost:8080/api/v1/analysis/5674348a-e42a-475c-ac74-ca5f69289f47/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTM4NDI1MjMsImlhdCI6MTc1Mzc5OTMyMywiaWQiOjEsIm5hbWUiOiLQmNCy0LDQvSDQmNCy0LDQvdC-0LIiLCJlbWFpbCI6Iml2YW5AZXhhbXBsZS5jb20ifQ.DV8Y25vv-llWuFQaqPPpNB42iosE2YZgsqjCBZV5t3U
Content-Type: application/json

{
  "sender": "user",
  "message": "Пример сообщения для чата"
}
